# -*- coding: utf-8 -*-
"""Assignment-3-DecisionTree.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BPkHxIOr_LghbmT7KqspMjt1KUN4JOf4

# Assignment 3: Decision Tree and Random Forest {-}

This assignment aims at familiarizing you with training and testing Decision Tree and Random Forest classification model. Here are the BASIC requirements of the assignment:

- Load the data.
- Analyze the data.
- Check if the data is imbalanced, possibly apply SMOTE to oversample or undersample data classes.
- Use GridSearchCV to find the best Decision Tree and Random Forest.
- Show the most important features.
- Visualize the tree.


The dataset you will be working on is 'data-employee-recruitment.csv'. It is composed of attributes such as employee gender, education level, company size, etc., to develop an employee recruitment prediction model.

### Submission {-}
The structure of submission folder should be organized as follows:

- ./\<StudentID>-assignment3-notebook.ipynb: Jupyter notebook containing source code.

The submission folder is named ML4DS-\<StudentID>-Assignment3 (e.g., ML4DS-2012345-Assigment3) and then compressed with the same name.
    
### Evaluation {-}
Assignment evaluation will be conducted on how you accomplish the assignment requirements. It is a plus if you have data exploration and modeling steps other than the basic requirements. In addition, your code should conform to a Python coding convention such as PEP-8.

### Deadline {-}
Please visit Canvas for details.

## Load libraries and data
"""

# Load Pandas library
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

!pip install graphviz scikit-learn
from sklearn.tree import plot_tree
import matplotlib.pyplot as plt

# Load the dataset
df = pd.read_csv("data-employee-recruitment.csv")

df.head()

df.info()

"""A company is looking for potential candidates from a pool of training program attendants. The dataset contains attendant background (demographics, current company, i.e., data features) and whether he or she is looing for a job change (data label). The company wants to build a prediction model using this dataset. Here follows the data dictionary:

* enrollee_id : unique ID for candidate
* city_development_index : developement index of the city (scaled)
* gender: gender of candidate
* relevent_experience: relevant experience of candidate
* enrolled_university: type of university course enrolled if any
* education_level: education level of candidate
* major_discipline: education major discipline of candidate
* experience: candidate's total experience in years
* company_size: number of employees in the current company of candidate
* company_type : Type of current employer
* last_new_job: difference in years between previous job and current job
* training_hours: training hours completed
* target value: 0 – not looking for job change, 1 – looking for a job change

## Encoding
"""

# Discard the first columns
df = df.iloc[:, 1:]
df.head()

# Encode ordinal variables

# Last new jobs
print("original unique data for last_new_job:", df['last_new_job'].unique())
df['last_new_job'] = df['last_new_job'].replace({'never': 0, '>4': 5}).astype(int)
print("encoded data:", df['last_new_job'].unique(), "\n")

# Experience
print("original unique data for experience:", df['experience'].unique())
df['experience'] = df['experience'].replace({'<1': 0, '>20': 21}).astype(int)
print("encoded data:", df['experience'].unique(), "\n")

# Company size
print("original unique data for company_size:", df['company_size'].unique())
company_size_midpoint = {
    '<10': 5,
    '10/49': 25,
    '50-99': 75,
    '100-500': 250,
    '500-999': 750,
    '1000-4999': 2500,
    '5000-9999': 7500,
    '10000+': 25000,
}
df['company_size'] = df['company_size'].map(company_size_midpoint)
print("encoded data:", df['company_size'].unique(), "\n")

# Education Level
print("original unique data for education_level:", df['education_level'].unique())
mapping = {'Graduate': 0, 'Masters': 1, 'Phd': 2}
df['education_level'] = df['education_level'].map(mapping)
print("encoded data:", df['education_level'].unique())

# prompt: call the row that has negative value in column training hour, count number of row
print("Number of rows that has negative training hours: ", len(df[df['training_hours'] < 0]), "\n")
df[df['training_hours'] < 0].head()

# Delete row that has negative value in training hours column
df = df[df['training_hours'] >= 0]
df.head()

"""## EDA"""

df.info()

df.describe()

# Visualize the distributions of numerical columns
numerical_cols = df.select_dtypes(include=['int64', 'float64']).columns.tolist()
numerical_cols.remove('target')

df[numerical_cols].hist(figsize=(10, 8))
plt.tight_layout()
plt.show()

# Visualize the distributions of categorical columns
categorical_cols = df.select_dtypes(include=['object', 'category']).columns.tolist()

for col in categorical_cols:
  plt.figure(figsize=(10, 4))
  sns.countplot(data=df, x=col)
  plt.title(f'Distribution of {col}')
  plt.xticks(rotation=0, ha='right')
  plt.tight_layout()
  plt.show()

# Plot the distribution of the target column
plt.figure(figsize=(6, 4))
sns.countplot(x='target', data=df)
plt.title('Distribution of Target Variable')
plt.xlabel('Target (0: Not seeking job change, 1: Seeking job change)')
plt.ylabel('Count')
plt.show()

"""-> Pretty balanced, no need to apply SMOTE

## Pre process data
"""

# Separate features and target
X = df.drop('target', axis=1)
y = df['target']

# Identify categorical and numerical columns
categorical_cols = X.select_dtypes(include='object').columns
numerical_cols = X.select_dtypes(include=['int64', 'float64']).columns

# Create a preprocessor to handle categorical and numerical features
preprocessor = ColumnTransformer(
    transformers=[
        ('num', 'passthrough', numerical_cols),
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_cols)])
print("X:", X.columns)
print("y:", y.name)

# Define the parameter grid for Decision Tree
dt_param_grid = {
    'classifier__max_depth': [None, 5, 10, 20],
    'classifier__min_samples_split': [2, 5, 10],
    'classifier__min_samples_leaf': [1, 2, 4]
}

# Define the parameter grid for Random Forest
rf_param_grid = {
    'classifier__n_estimators': [50, 100, 200],
    'classifier__max_depth': [None, 5, 10, 20],
    'classifier__min_samples_split': [2, 5, 10],
    'classifier__min_samples_leaf': [1, 2, 4]
}

# Create pipelines for Decision Tree and Random Forest
dt_pipeline = Pipeline(steps=[('preprocessor', preprocessor),
                              ('classifier', DecisionTreeClassifier(random_state=42))])

rf_pipeline = Pipeline(steps=[('preprocessor', preprocessor),
                              ('classifier', RandomForestClassifier(random_state=42))])

"""## Training"""

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

X_train.head()

"""## Use GridSearchCV to find the best Decision Tree and Random Forest.

"""

# Use GridSearchCV to find the best Decision Tree
dt_grid_search = GridSearchCV(dt_pipeline, dt_param_grid, cv=5, scoring='accuracy', n_jobs=-1)
dt_grid_search.fit(X_train, y_train)

print("Best parameters for Decision Tree:", dt_grid_search.best_params_)
print("Best cross-validation score for Decision Tree:", dt_grid_search.best_score_)

# Use GridSearchCV to find the best Random Forest
rf_grid_search = GridSearchCV(rf_pipeline, rf_param_grid, cv=5, scoring='accuracy', n_jobs=-1)
rf_grid_search.fit(X_train, y_train)

print("\nBest parameters for Random Forest:", rf_grid_search.best_params_)
print("Best cross-validation score for Random Forest:", rf_grid_search.best_score_)

# You can access the best models like this:
best_dt_model = dt_grid_search.best_estimator_
best_rf_model = rf_grid_search.best_estimator_

"""## Show the most important features"""

# Show most important features from the best Random Forest model
best_rf_classifier = best_rf_model.named_steps['classifier']
feature_importances = best_rf_classifier.feature_importances_

# Get the names of the features after one-hot encoding
ohe = best_rf_model.named_steps['preprocessor'].named_transformers_['cat']
feature_names_cat = ohe.get_feature_names_out(categorical_cols)
feature_names_num = numerical_cols

all_feature_names = list(feature_names_num) + list(feature_names_cat)

# Create a pandas Series for easier analysis
feature_importance_series = pd.Series(feature_importances, index=all_feature_names)

# Sort features by importance
sorted_feature_importance = feature_importance_series.sort_values(ascending=False)

# Plot the feature importances
plt.figure(figsize=(10, 4))
sorted_feature_importance.head(6).plot(kind='barh')
plt.title('Top 6 Most Important Features (Random Forest)')
plt.xlabel('Importance')
plt.ylabel('Feature')
plt.gca().invert_yaxis() # To have the most important feature at the top
plt.show()

Train

"""## Visualize"""



# Access the fitted Decision Tree classifier from the pipeline
fitted_dt_classifier = best_dt_model.named_steps['classifier']

# Get the feature names after preprocessing (one-hot encoding)
# We need to fit the preprocessor on the training data to get the column names
preprocessor.fit(X_train)
feature_names = preprocessor.get_feature_names_out()

plt.figure(figsize=(20,10))
plot_tree(fitted_dt_classifier, feature_names=all_feature_names, filled=True, class_names=['0', '1'], fontsize=5)
plt.title("Decision Tree Visualization")
plt.show()

"""## Evaluate"""

# Evaluate the best Decision Tree model on the test set
dt_test_score = best_dt_model.score(X_test, y_test)
print("Test set accuracy for Best Decision Tree:", dt_test_score)

# Evaluate the best Random Forest model on the test set
rf_test_score = best_rf_model.score(X_test, y_test)
print("Test set accuracy for Best Random Forest:", rf_test_score)

"""# Failed dtreeviz"""