# -*- coding: utf-8 -*-
"""dtreeviz.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g_C4ecVoqAq2YUNGxsdOWsWtzIv8p6Co
"""

!pip install --upgrade dtreeviz

from dtreeviz import dtreeviz
import pandas as pd

Xs = df[numerical_cols]

# Create a preprocessor that only handles numerical features
numerical_only_preprocessor = ColumnTransformer(
    transformers=[
        ('num', 'passthrough', numerical_cols)])

# Create a new pipeline for Decision Tree using only numerical columns
dt_numerical_pipeline = Pipeline(steps=[('preprocessor', numerical_only_preprocessor),
                                        ('classifier', DecisionTreeClassifier(random_state=42))])

# Define the parameter grid for Decision Tree (can reuse the previous one)
dt_param_grid_numerical = {
    'classifier__max_depth': [None, 5, 10, 20],
    'classifier__min_samples_split': [2, 5, 10],
    'classifier__min_samples_leaf': [1, 2, 4]
}

# Use GridSearchCV to find the best Decision Tree on numerical columns only
dt_grid_search_numerical = GridSearchCV(dt_numerical_pipeline, dt_param_grid_numerical, cv=5, scoring='accuracy', n_jobs=-1)
dt_grid_search_numerical.fit(Xs, y_train)

print("Best parameters for Decision Tree (numerical only):", dt_grid_search_numerical.best_params_)
print("Best cross-validation score for Decision Tree (numerical only):", dt_grid_search_numerical.best_score_)

# You can access the best numerical-only DT model like this:
best_dt_numerical_model = dt_grid_search_numerical.best_estimator_

fitted_dt_numerical_classifier = best_dt_numerical_model.named_steps['classifier']

# Create a richer visualization:
array = Xs.to_numpy()

viz = dtreeviz(
    fitted_dt_numerical_classifier,
    X_train=Xs,
    y_train=y_train,
    target_name="target",
    feature_names=numerical_cols,
    class_names=["0.0", "1.0"])

viz.view()  # or viz.save("tree.svg")